version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'sglabdev'
      POSTGRES_PASSWORD: 'SgLab*2025'
      POSTGRES_DB: 'sglabdeskdb'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@sglab.dev'
      PGADMIN_DEFAULT_PASSWORD: 'SgLab*2025'
    ports:
      - "5050:80"
  app:
    build: .
    container_name: sglabapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sglabdeskdb
      SPRING_DATASOURCE_USERNAME: sglabdev
      SPRING_DATASOURCE_PASSWORD: SgLab*2025

volumes:
  postgres_data:
