spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sglabdeskdb
    username: 'sglabdev'
    password: 'SgLab*2025'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: mail.gurkangultekin.dev
    port: 587
    username: info@gurkangultekin.dev
    password: Gprt.5167

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

