spring:
  datasource:
    url: jdbc:postgresql://dpg-cvjung6uk2gs73a3hbc0-a.frankfurt-postgres.render.com:5432/deskdb_xm2s
    username: deskdb_xm2s_user
    password: xgsizYhjhNZwFawrzqF1VUmyLURN2hIz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://dpg-cvjuepd6ubrc73cq8gcg-a.frankfurt-postgres.render.com:5432/deskdb_dbvj
    user: deskdb_dbvj_user
    password: OPA1T2PMtAUc86SKQyEexC6tUOPtvI5Z

  mail:
    host: mail.gurkangultekin.dev
    port: 587
    username: info@gurkangultekin.dev
    password: Gprt.5167

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
